### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by lskatz** [supernifty/gustle#1]
Hi, I am trying out cgMLST callers and saw this one.  Is it still active?  I see a TODO list at the end.

**Comment by supernifty** [comment]
Thanks @lskatz for your interest! Unfortunately I am not actively developing this any more but I wasn't far off a usable release. If you are interested in progressing this please feel free to fork or add to this repository. Mentioning @tseemann since he was initially involved in this project.

**Comment by lskatz** [comment]
Thanks for letting me know!  I took your idea for inspiration today and put it into a couple of scripts.  It's fast!  https://github.com/lskatz/hashest

**Comment by supernifty** [comment]
Very cool! That is awesome. And thanks so much for the mention :)
